---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'certdb/**'
      - 'debian/**'
      - 'demo/**'
      - 'doc/**'
      - 'js/**'
      - 'prototypes/**'
      - 'python/**'
      - 'systemd/**'
      - 'tools/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'certdb/**'
      - 'debian/**'
      - 'demo/**'
      - 'doc/**'
      - 'js/**'
      - 'prototypes/**'
      - 'python/**'
      - 'systemd/**'
      - 'tools/**'
    branches:
      - master
env:
  CC: 'ccache gcc-10'
  CXX: 'ccache g++-10'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.type }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            g++-10 \
            libattr1-dev \
            libavahi-client-dev \
            libboost-dev \
            libc-ares-dev \
            libcap-dev \
            libcurl4-openssl-dev \
            libdbus-1-dev \
            libgtest-dev \
            libluajit-5.1-dev \
            libnfs-dev \
            libnghttp2-dev \
            libpcre2-dev \
            libpq-dev \
            libseccomp-dev \
            libsodium-dev \
            libssl-dev \
            libsystemd-dev \
            libyaml-cpp-dev

      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          setup-options: -Ddocumentation=disabled -Dstatic_libcxx=true -Dcertdb=true -Dhttp2=enabled -Dnfs=enabled -Dwas=enabled -Dyaml=enabled -Dzeroconf=enabled --force-fallback-for=libcm4all-was-protocol
          meson-version: 0.56.0

      - name: Unit Tests
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          setup-options: -Ddocumentation=disabled -Dstatic_libcxx=true -Dcertdb=true -Dhttp2=enabled -Dnfs=enabled -Dwas=enabled -Dyaml=enabled -Dzeroconf=enabled --force-fallback-for=libcm4all-was-protocol
          meson-version: 0.56.0
